// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodcore.Models
{
    public partial class Menu
    {
        public Menu()
        {
            Orders = new HashSet<Order>();
        }

        public string Itemid { get; set; }
        public string Itemname { get; set; }
        public string Itemdesc { get; set; }
        public int? Price { get; set; }
        public string Images { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}