// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodcore.Models
{
    public partial class Mycart
    {
        public int Cartid { get; set; }
        public string Username { get; set; }
        public string Itemcode { get; set; }
    }
}