// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foodcore.Models
{
    public partial class Order
    {
        public int Orderid { get; set; }
        public string Username { get; set; }
        public string Itemid { get; set; }
        public int? Qty { get; set; }
        public int? Price { get; set; }

        public virtual Menu Item { get; set; }
        public virtual Register UsernameNavigation { get; set; }
    }
}